name: Star Notify
on:
  fork:
    branches:
      - main
  watch:
    types: [ started ]
jobs:
  Notify:
    runs-on: ubuntu-latest
    steps:
      - name: Install Dependencies
        run: |
          pip install yagmail[all] requests
      - name: Download Scripts
        run: |
          wget https://raw.githubusercontent.com/foyoux/aligo/main/.github/workflows/star_notify.py#${{github.job}}
      - name: Send EMail
        run: |
          python star_notify.py ${{secrets.POST_EMAIL}} ${{secrets.POST_EAMIL_TOKEN}} ${{secrets.NOTIFY_EMAIL}} ${{github.token}}